version: '3.4'

services:
  monstache:
    volumes:
      - ./monstache/monstache.config.toml:/app/monstache.config.toml
    ports:
      - "8080:8080"
  mongo0:
    expose:
      - 30000
    ports:
      - 30000:30000
    volumes:
      - 'mongodb_repl_data1:/data/db:z'
    command: "--bind_ip_all --replSet rs0 --port 30000"
  mongo1:
    expose:
      - 30001
    ports:
      - 30001:30001
    volumes:
      - 'mongodb_repl_data2:/data/db:z'
    command: "--bind_ip_all --replSet rs0 --port 30001"
  mongo2:
    expose:
      - 30002
    ports:
      - 30002:30002
    volumes:
      - 'mongodb_repl_data3:/data/db:z'
    command: "--bind_ip_all --replSet rs0 --port 30002"
  es7:
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    restart: unless-stopped
  dito.autocomplete:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "32809:80"
      - "32808:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro