version: '3.4'

volumes:
  esdata1:
    driver: local
  mongodb_repl_data1:
    driver: local
  mongodb_repl_data2:
    driver: local
  mongodb_repl_data3:
    driver: local
services:
  monstache:
    image: rwynn/monstache:6.4.1
    container_name: monstache
    working_dir: /app
    command: -f ./monstache.config.toml
    depends_on:
      - mongo0
      - mongo1
      - mongo2
      - es7
    healthcheck:
      test: "wget -q -O - http://localhost:8080/healthz"
      interval: 10s
      timeout: 30s
      retries: 300
    restart: unless-stopped
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo:latest
    restart: always
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:latest
    restart: always
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:latest
    restart: always
  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.5.1
    container_name: elasticsearch
  dito.autocomplete:
    image: ${DOCKER_REGISTRY-}ditoautocomplete
    build:
      context: .
      dockerfile: Dito.Autocomplete/Dockerfile
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo0
      - mongo1
      - mongo2